// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_RsendUDP_RCPPEXPORTS_H_GEN_
#define RCPP_RsendUDP_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace RsendUDP {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("RsendUDP", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("RsendUDP", "_RsendUDP_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in RsendUDP");
            }
        }
    }

    inline int sendUDP(std::string serverIP, int port, std::string message) {
        typedef SEXP(*Ptr_sendUDP)(SEXP,SEXP,SEXP);
        static Ptr_sendUDP p_sendUDP = NULL;
        if (p_sendUDP == NULL) {
            validateSignature("int(*sendUDP)(std::string,int,std::string)");
            p_sendUDP = (Ptr_sendUDP)R_GetCCallable("RsendUDP", "_RsendUDP_sendUDP");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sendUDP(Shield<SEXP>(Rcpp::wrap(serverIP)), Shield<SEXP>(Rcpp::wrap(port)), Shield<SEXP>(Rcpp::wrap(message)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

}

#endif // RCPP_RsendUDP_RCPPEXPORTS_H_GEN_
