# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Send a message in a UDP packet
#'
#' @param serverIP Destination IP address
#' @param port Destination port number
#' @param message Message string
#' @return success_status
#' @export
sendUDP <- function(serverIP, port, message) {
    .Call(`_RsendUDP_sendUDP`, serverIP, port, message)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_RsendUDP_RcppExport_registerCCallable`)
})
