# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Send a message in a UDP packet from R. Returns status, 0 = no error
#'
#' @export
sendUDP <- function(serverIP, port, message) {
    .Call('_RsendUDP_sendUDP', PACKAGE = 'RsendUDP', serverIP, port, message)
}

